added animations to the about us page
anushbhatia/Social-Scheduler pull request #62
Opened 2020-08-28 15:07 UTC by kartikeya-123

I have made some changes as suggested by @smaranjitghose . Please check it.

2020-08-28 20:22 UTC, anushbhatia requested changes
text not visible in subheading please remove that

2020-08-29 10:14 UTC, kartikeya-123 commented
> text not visible in subheading please remove that
   I have made the suggested changes.

2020-08-31 19:09 UTC, anushbhatia commented
Resolve conflict @abhu-A-J @ashishnagpal2498 merge them

2020-09-01 18:32 UTC, ashishnagpal2498 commented
Okay. I will merge it once @abhu-A-J will resolve the conflicts.

2020-09-04 15:17 UTC, anushbhatia commented
@kartikeya-123 you can resolve the conflict

2020-09-05 09:58 UTC, ashishnagpal2498 requested changes

2020-09-05 09:58 UTC, ashishnagpal2498 commented on src/components/About.jsx
> +  // box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.5);
Remove this comment

2020-09-05 09:58 UTC, ashishnagpal2498 commented on src/components/About.jsx
> -    /* height: 50em; */
This.

2020-09-05 09:58 UTC, ashishnagpal2498 commented on src/components/About.jsx
> -    /* height: 50em; */
Remove all code comments from your code.

2020-09-05 09:58 UTC, ashishnagpal2498 commented on src/components/About.jsx
> +  display: flex;
No Need of these properties,
width , display , margin. You are mixing properties unnecessarily.

2020-09-05 10:00 UTC, ashishnagpal2498 commented
You are mixing a whole bunch of CSS properties, which are not required. Kindly open inspect and look for those properties and remove them. Self review your code first.

2020-09-17 18:36 UTC, ashishnagpal2498 commented
@kartikeya-123 . If you don't reply to the conversation. Unfortunately I have to close this PR.

2020-10-06 13:29 UTC, closed without merging